# Generated by Django 2.0.4 on 2018-04-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_auto_20180409_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=30, null=True)),
                ('tokenCode', models.IntegerField()),
            ],
        ),
    ]
