# Generated by Django 2.0.4 on 2018-04-24 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
    ]
