# Generated by Django 2.0.3 on 2018-04-20 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_auto_20180421_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
    ]
