# Generated by Django 2.0.4 on 2018-04-24 04:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_image_popularity'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='likeby',
            field=models.ManyToManyField(blank=True, related_name='likeby', to=settings.AUTH_USER_MODEL),
        ),
    ]
