# Generated by Django 2.0.3 on 2018-03-27 04:10

from django.db import migrations, models
import django.db.models.deletion
import mainApp.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[['Abstract', 'Abstract'], ['Aerial', 'Aerial'], ['Animals', 'Animals'], ['Architecture', 'Architecture'], ['Black and White', 'Black and White'], ['Family', 'Family'], ['Fashion', 'Fashion'], ['Fine Art', 'Fine Art'], ['Food', 'Food'], ['Journalism', 'Journalism'], ['Landscape', 'Landscape'], ['Macro', 'Macro'], ['Nature', 'Nature'], ['Night', 'Night'], ['People', 'People'], ['Performing Arts', 'Performing Arts'], ['Sport', 'Sport'], ['Still Life', 'Still Life'], ['Street', 'Street'], ['Travel', 'Travel']], max_length=30)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30)),
                ('description', models.TextField(blank=True, max_length=150)),
                ('image', models.ImageField(upload_to='images/', validators=[mainApp.validators.validate_file_extension])),
                ('uploadtime', models.DateField(auto_now_add=True)),
                ('like_stats', models.IntegerField(default=0)),
                ('download_stats', models.IntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=15)),
                ('avatar', models.ImageField(upload_to='avatars/', validators=[mainApp.validators.validate_file_extension])),
                ('email', models.EmailField(max_length=30)),
                ('self_description', models.TextField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.User'),
        ),
        migrations.AddField(
            model_name='image',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Member'),
        ),
        migrations.AddField(
            model_name='image',
            name='tag',
            field=models.ManyToManyField(to='mainApp.Tag'),
        ),
        migrations.AddField(
            model_name='image',
            name='user',
            field=models.ManyToManyField(to='mainApp.User'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='image',
            field=models.ManyToManyField(to='mainApp.Image'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='tag',
            field=models.ManyToManyField(to='mainApp.Tag'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='user',
            field=models.ManyToManyField(to='mainApp.User'),
        ),
    ]
