# Generated by Django 2.0.4 on 2018-04-08 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mainApp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20180327_2159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='member',
            name='email',
        ),
        migrations.RemoveField(
            model_name='member',
            name='password',
        ),
        migrations.RemoveField(
            model_name='member',
            name='username',
        ),
        migrations.AlterField(
            model_name='member',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars/', validators=[mainApp.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='member',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
